Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
monte_carlo_df = monte_carlo_df.set_crs(epsg = 2056)
wald = wald.set_crs(epsg = 2056,allow_override = True)

monte_carlo_sjoin = gpd.sjoin(wald,monte_carlo_df)

monte_carlo_sjoin.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-2-b43b9d39760e>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mwald[0m [0;34m=[0m [0mwald[0m[0;34m.[0m[0mset_crs[0m[0;34m([0m[0mepsg[0m [0;34m=[0m [0;36m2056[0m[0;34m,[0m[0mallow_override[0m [0;34m=[0m [0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[0;32m----> 4[0;31m [0mmonte_carlo_sjoin[0m [0;34m=[0m [0mgpd[0m[0;34m.[0m[0msjoin[0m[0;34m([0m[0mwald[0m[0;34m,[0m[0mmonte_carlo_df[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0mmonte_carlo_sjoin[0m[0;34m.[0m[0mhead[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/geopandas/tools/sjoin.py[0m in [0;36msjoin[0;34m(left_df, right_df, how, op, lsuffix, rsuffix)[0m
[1;32m     86[0m             [0;31m# keep them the same[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     87[0m             [0mpredicate[0m [0;34m=[0m [0mop[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 88[0;31m             [0msindex[0m [0;34m=[0m [0mright_df[0m[0;34m.[0m[0msindex[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     89[0m             [0minput_geoms[0m [0;34m=[0m [0mleft_df[0m[0;34m.[0m[0mgeometry[0m[0;34m[0m[0;34m[0m[0m
[1;32m     90[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/geopandas/base.py[0m in [0;36msindex[0;34m(self)[0m
[1;32m    591[0m     [0;32mdef[0m [0msindex[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    592[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_sindex_generated[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 593[0;31m             [0mself[0m[0;34m.[0m[0m_generate_sindex[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    594[0m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_sindex[0m[0;34m[0m[0;34m[0m[0m
[1;32m    595[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/geopandas/base.py[0m in [0;36m_generate_sindex[0;34m(self)[0m
[1;32m     96[0m [0;34m[0m[0m
[1;32m     97[0m     [0;32mdef[0m [0m_generate_sindex[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 98[0;31m         [0msindex_cls[0m [0;34m=[0m [0mget_sindex_class[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     99[0m         [0;32mif[0m [0msindex_cls[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    100[0m             [0m_sindex[0m [0;34m=[0m [0msindex_cls[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mgeometry[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/geopandas/sindex.py[0m in [0;36mget_sindex_class[0;34m()[0m
[1;32m     41[0m         [0;32mreturn[0m [0mRTreeIndex[0m[0;34m[0m[0;34m[0m[0m
[1;32m     42[0m     raise ImportError(
[0;32m---> 43[0;31m         [0;34m"Spatial indexes require either `rtree` or `pygeos`. "[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     44[0m         [0;34m"See installation instructions at https://geopandas.org/install.html"[0m[0;34m[0m[0;34m[0m[0m
[1;32m     45[0m     )

[0;31mImportError[0m: Spatial indexes require either `rtree` or `pygeos`. See installation instructions at https://geopandas.org/install.html
ImportError: Spatial indexes require either `rtree` or `pygeos`. See installation instructions at https://geopandas.org/install.html

